name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package
        run: pip install --upgrade .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx nbsphinx nbsphinx_link sphinx_rtd_theme

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Build documentation
        run: |
          cd Docs
          make html
          touch build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Docs/build/html
          SINGLE_COMMIT: true
          TARGET_FOLDER: >-
            ${{ 
              github.event_name == 'push' && github.ref == 'refs/heads/main'
              ? ''
              : 'pr-preview' 
            }}
